DROP DATABASE IF EXISTS foodorder;
CREATE DATABASE foodorder;

\c foodorder;

CREATE SEQUENCE id_seq;
 
CREATE TABLE USER_PROFILE (
    USER_ID integer NOT NULL DEFAULT nextval('id_seq'),
    USER_NAME VARCHAR(50),
    QTY INTEGER,
    ITEM VARCHAR(50)
);
 
ALTER SEQUENCE id_seq
OWNED BY USER_PROFILE.USER_ID;